name: CI Pipeline
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build project
        run: npm run build
      - name: Create a text file named 21CSR208
        run: echo "This is a text file" > 21CSR208.txt
      - name: Print the current working directory
        run: pwd
      - name: List all files and directories with detailed information
        run: ls -la
      - name: Display the current date and time
        run: date
